// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: genservice/genservice.proto

package generated_service_v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *GS) Reset() {
	*x = GS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genservice_genservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS) ProtoMessage() {}

func (x *GS) ProtoReflect() protoreflect.Message {
	mi := &file_genservice_genservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS.ProtoReflect.Descriptor instead.
func (*GS) Descriptor() ([]byte, []int) {
	return file_genservice_genservice_proto_rawDescGZIP(), []int{0}
}

func (x *GS) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_genservice_genservice_proto protoreflect.FileDescriptor

var file_genservice_genservice_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x65, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x65, 0x6e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x12, 0x0a, 0x02, 0x47, 0x53, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x32, 0x50, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x46,
	0x6f, 0x6f, 0x42, 0x61, 0x72, 0x12, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x53, 0x1a,
	0x18, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x53, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x73, 0x70, 0x69, 0x65,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2f, 0x67,
	0x65, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genservice_genservice_proto_rawDescOnce sync.Once
	file_genservice_genservice_proto_rawDescData = file_genservice_genservice_proto_rawDesc
)

func file_genservice_genservice_proto_rawDescGZIP() []byte {
	file_genservice_genservice_proto_rawDescOnce.Do(func() {
		file_genservice_genservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_genservice_genservice_proto_rawDescData)
	})
	return file_genservice_genservice_proto_rawDescData
}

var file_genservice_genservice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_genservice_genservice_proto_goTypes = []interface{}{
	(*GS)(nil), // 0: generated.service.v1.GS
}
var file_genservice_genservice_proto_depIdxs = []int32{
	0, // 0: generated.service.v1.GeneratedService.FooBar:input_type -> generated.service.v1.GS
	0, // 1: generated.service.v1.GeneratedService.FooBar:output_type -> generated.service.v1.GS
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_genservice_genservice_proto_init() }
func file_genservice_genservice_proto_init() {
	if File_genservice_genservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genservice_genservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genservice_genservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genservice_genservice_proto_goTypes,
		DependencyIndexes: file_genservice_genservice_proto_depIdxs,
		MessageInfos:      file_genservice_genservice_proto_msgTypes,
	}.Build()
	File_genservice_genservice_proto = out.File
	file_genservice_genservice_proto_rawDesc = nil
	file_genservice_genservice_proto_goTypes = nil
	file_genservice_genservice_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeneratedServiceClient is the client API for GeneratedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratedServiceClient interface {
	FooBar(ctx context.Context, in *GS, opts ...grpc.CallOption) (*GS, error)
}

type generatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratedServiceClient(cc grpc.ClientConnInterface) GeneratedServiceClient {
	return &generatedServiceClient{cc}
}

func (c *generatedServiceClient) FooBar(ctx context.Context, in *GS, opts ...grpc.CallOption) (*GS, error) {
	out := new(GS)
	err := c.cc.Invoke(ctx, "/generated.service.v1.GeneratedService/FooBar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratedServiceServer is the server API for GeneratedService service.
type GeneratedServiceServer interface {
	FooBar(context.Context, *GS) (*GS, error)
}

// UnimplementedGeneratedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGeneratedServiceServer struct {
}

func (*UnimplementedGeneratedServiceServer) FooBar(context.Context, *GS) (*GS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FooBar not implemented")
}

func RegisterGeneratedServiceServer(s *grpc.Server, srv GeneratedServiceServer) {
	s.RegisterService(&_GeneratedService_serviceDesc, srv)
}

func _GeneratedService_FooBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratedServiceServer).FooBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generated.service.v1.GeneratedService/FooBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratedServiceServer).FooBar(ctx, req.(*GS))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeneratedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generated.service.v1.GeneratedService",
	HandlerType: (*GeneratedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FooBar",
			Handler:    _GeneratedService_FooBar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genservice/genservice.proto",
}
